base: /
title: Lumen Pink # Site title
sitename: A nova rede social da Lumen # Site name
support: # File extensions which will be parsed (must be an array)
  - md
  - txt
  - html
  - htm
buildall: true # Whether to build pages without frontmatter
outputdir: public # Output directory
contentdir: content # Content directory
#  (there's a bug in the YAML interpreter that prevents 
# parsing when comments are in the same line as short arrays) 
defaultcategory: "General" # Default category 
lang: [ pt-br, en, es ]  # Supported languages (must be an array - first is the default)
fqdn: https://lumen.pink # FQDN without trailing slash
author: ~lumen # Author name
htmlpostprocessing: minify # minify or beautify or none

kinds:
  note:
    content_dir: notas
    title:
      pt-br: Notas
      en: Notes
      es: Notas
    palette:
      bg: '#E8EDE7'
      fg: '#2A3B2C'
    has_title: false
    show_on_home: true
    display_mode: full_content
  photo:
    content_dir: fotos
    title:
      pt-br: Fotos
      en: Photos
      es: Fotos
    palette:
      bg: '#E6EDF2'
      fg: '#1C3A5A'
    has_title: false
    show_on_home: true
    display_mode: thumbnail_snippet
  article:
    content_dir: artigos
    title:
      pt-br: Artigos
      en: Articles
      es: Artículos
    palette:
      bg: '#FDF6E3'
      fg: '#3A2E2A'
    has_title: true
    show_on_home: true
    display_mode: default
  jardim:
    content_dir: jardim
    title:
      pt-br: Jardim
      en: Garden
      es: Jardín
    palette:
      bg: '#F0EAE1'
      fg: '#5C3A21'
    has_title: true
    show_on_home: false
    display_mode: default
translations:
  Home:
    pt: Início
    en: Home
    es: Inicio
  Index:
    pt: Índice
    en: Index
    es: Índice
  Now:
    pt: Agora
    en: Now
    es: Ahora
  Recent posts:
    pt: Publicações recentes
    en: Recent posts
    es: Publicaciones recientes
  "Browse the sections of the site in Gopher style:":
    pt: "Navegue pelas seções do site no estilo Gopher:"
    en: "Browse the sections of the site in Gopher style:"
    es: "Navegue por las secciones del sitio en estilo Gopher:"
  Articles:
    pt: Artigos
    en: Articles
    es: Artículos
  Notes:
    pt: Notas
    en: Notes
    es: Notas
  Photos:
    pt: Fotos
    en: Photos
    es: Fotos
  Garden:
    pt: Jardim
    en: Garden
    es: Jardín
  About:
    pt-br: Sobre
    en: About
    es: Sobre
  now:
    pt-br: agora
    en: now
    es: ahora
  about-the-blog:
    pt-br: sobre-o-blog
    en: about-the-blog
    es: sobre-el-blog
  Maturity:
    pt: Maturidade
    en: Maturity
    es: Madurez
  Reliability:
    pt: Confiabilidade
    en: Reliability
    es: Confiabilidad