<?php
/** @var \Indieinabox\Page $page */
/** @var \Indieinabox\Site $site */
?>
<!DOCTYPE html>
<html lang="<?= $page->lang ?>">
<head>
    <?php include('includes/head.php'); ?>
</head>
<body>
    <?php include('includes/header.php'); ?>
    
    <main>
        <article class="h-entry">
            <?php if (!in_array($page->kind, ['note', 'photo'])): ?>
                <h1 class="p-name"><?= htmlspecialchars($page->title) ?></h1>
            <?php endif; ?>
            
            <?php
            // Only show date metadata when the page has a real author-assigned date.
            // Section index pages generated by SiteBuilder have no date set, so their
            // localizeddate falls back to the Localization default sentinel value.
            $hasRealDate = !empty($page->isodate)
                && $page->localizeddate !== 'Saturday, January 1 of 2001, 00:00 UTC';
            ?>
            <?php if ($hasRealDate): ?>
            <div class="post-metadata">
                <time class="dt-published" datetime="<?= $page->isodate ?>"><?= $page->localizeddate ?></time>
                <?php if ($page->kind === 'jardim'): ?>
                    <?php if (isset($page->metadata->maturity)): ?>
                        • <?= \Indieinabox\Helper::translate('Maturidade') ?>: <?= htmlspecialchars($page->metadata->maturity) ?>
                    <?php endif; ?>
                    <?php if (isset($page->metadata->reliability)): ?>
                        • <?= \Indieinabox\Helper::translate('Confiabilidade') ?>: <?= htmlspecialchars($page->metadata->reliability) ?>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            
            <div class="e-content">
                <?= $page->content ?>
            </div>
        </article>
    </main>
    
    <?php include('includes/footer.php'); ?>
</body>
</html>
